<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_About this page_a-zes0xwp42i73</name>
   <tag></tag>
   <elementGuidId>830c86ba-492e-472e-9948-f56171643005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-zes0xwp42i73']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-zes0xwp42i73&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-zes0xwp42i73&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>756d21e7-8a53-4e4e-816f-b998f244cb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>164d2be7-1f2e-44fe-82fe-c731b4566cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>5b2186bb-da2a-4fa3-93fd-60b3afff85d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>c082f2c9-cb32-4706-bd32-0c430724b6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>8b10752f-8770-488d-af85-513b5b47188e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-zes0xwp42i73</value>
      <webElementGuid>95ee1687-ff93-4b33-92ac-1b3efa8015c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0e03e737-9333-4a05-8bb7-275de6698f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>0656d96d-6594-48b0-bc0f-2405c441f688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>61bfb281-0aa7-414e-953a-edb7b79b41b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=bUO1BXI8H9PgjAPSW9hwuSeI&amp;size=normal&amp;s=XKdrVhVI3vMbhgqBgjCWY5EUh9BAAXCZYcYZIGMgLbILEjIv_Mkzm4fD3KI8nSkmBKMziKPuZOUweivBD8NVMD3CN8PCyTvYsLV8uOVCtgdPHt8Bb47xVQOc3Xf0jcHipeWIjPmwUicleAptYeWu_Y612Evhc-DHpnAh7dVA5gTniahsNGhfC7WcZjtFHzET8XwPnrBrCH6zm0FLEsYFQxhX6arJdF9UH-3ExHA9c4NUuNnEfkIu2qjg6v4HAE2Bx9tbfppxBsda6-JSYVWJ6IzaEKpuDuY&amp;cb=1ama0hz2eocj</value>
      <webElementGuid>74ac1ec9-d2a5-4731-b2fc-73ca6460db0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>2b9a0b63-647c-4d22-b4dd-69647860801a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-zes0xwp42i73']</value>
      <webElementGuid>ba0d9a95-fa39-4bd8-adc8-d9f38c7c5ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha']/div/div/iframe</value>
      <webElementGuid>2d72b455-74fc-4f51-8f30-589528860eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f6aa8146-46c4-4641-8fae-db3fa3d3d4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-zes0xwp42i73' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=en&amp;v=bUO1BXI8H9PgjAPSW9hwuSeI&amp;size=normal&amp;s=XKdrVhVI3vMbhgqBgjCWY5EUh9BAAXCZYcYZIGMgLbILEjIv_Mkzm4fD3KI8nSkmBKMziKPuZOUweivBD8NVMD3CN8PCyTvYsLV8uOVCtgdPHt8Bb47xVQOc3Xf0jcHipeWIjPmwUicleAptYeWu_Y612Evhc-DHpnAh7dVA5gTniahsNGhfC7WcZjtFHzET8XwPnrBrCH6zm0FLEsYFQxhX6arJdF9UH-3ExHA9c4NUuNnEfkIu2qjg6v4HAE2Bx9tbfppxBsda6-JSYVWJ6IzaEKpuDuY&amp;cb=1ama0hz2eocj']</value>
      <webElementGuid>83c15480-b2ca-415c-873e-63da0452d5e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
