<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bridges_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>a0e5fcb4-e98a-43a5-a4ec-c68c21c6ed19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3154e63e-9c52-4a20-b298-4c64fd1fd2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>01e7f689-c6d2-4a78-b917-622800a7cb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4AAJrPLY9cyqLYlj4WD5O5YTrktZyBA2lmMAglQPvbjw4Nh5Aq1MfK-mo9vjI9jHhjHW4iRPdvtHWNnzLjq_-E_4mAuMvtbN6rZWJgueGHHePZ_O5U68b9Fr3KT8r5ZMYuE3odVg2R_5ieHticRmKJwpcB0v0qezrY6UU3DxAPZ5ujsf1YXDcrbYu_m8bzV_jnPoTZ&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>f8290bda-af02-4642-84be-ca3c5804d9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>bab17008-1bdd-4f72-b99d-4e756135a34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Demo/Page_httpswww.google.comsearchqamazonsca_es_61545e/iframe_html1body1div2div4iframe1_c-zes0xwp42i73</value>
      <webElementGuid>f5882eb7-a6bf-4451-8fe5-b7a6337defca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>20f874d6-8c7a-4f8b-b491-e46f079dd824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4AAJrPLY9cyqLYlj4WD5O5YTrktZyBA2lmMAglQPvbjw4Nh5Aq1MfK-mo9vjI9jHhjHW4iRPdvtHWNnzLjq_-E_4mAuMvtbN6rZWJgueGHHePZ_O5U68b9Fr3KT8r5ZMYuE3odVg2R_5ieHticRmKJwpcB0v0qezrY6UU3DxAPZ5ujsf1YXDcrbYu_m8bzV_jnPoTZ&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[2]</value>
      <webElementGuid>f43c6035-013b-438c-9e7b-65b952c86dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>5a21f871-9565-4a7c-b744-66abcda3980b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4AAJrPLY9cyqLYlj4WD5O5YTrktZyBA2lmMAglQPvbjw4Nh5Aq1MfK-mo9vjI9jHhjHW4iRPdvtHWNnzLjq_-E_4mAuMvtbN6rZWJgueGHHePZ_O5U68b9Fr3KT8r5ZMYuE3odVg2R_5ieHticRmKJwpcB0v0qezrY6UU3DxAPZ5ujsf1YXDcrbYu_m8bzV_jnPoTZ&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>9e5c3a3d-41c1-4436-9fb9-6921ff1186b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
